export const COL_KO: Record<string, string> = {
  index: "이름",
  "*ID": "ID",
  "*Id": "ID",
  Id: "ID",
  NameStr: "이름 키",
  skill: "스킬",
  skilldesc: "설명 키",
  charclass: "직업",
  code: "코드",
  item: "베이스",
  set: "세트",
  rarity: "희귀도",
  spawnable: "드랍 가능",
  enabled: "활성화",
  disabled: "비활성",
  description: "설명",
  numinputs: "재료 수",
  "input 1": "재료 1",
  "input 2": "재료 2",
  "input 3": "재료 3",
  output: "결과",
  "output b": "결과 B",
  "output c": "결과 C",
  lvl: "아이템 레벨",
  "lvl req": "요구 레벨",
  reqlevel: "요구 레벨",
  maxlvl: "최대 레벨",
  version: "버전",
  Unique: "유니크 보정",
  Set: "세트 보정",
  Rare: "레어 보정",
  Magic: "매직 보정",
  NoDrop: "노드랍",
  Picks: "픽 횟수",
  "Treasure Class": "보물 클래스",
  group: "그룹",
  level: "레벨",
  "Level": "레벨",
  "Level(N)": "레벨(NM)",
  "Level(H)": "레벨(헬)",
  type: "유형",
  namestr: "이름 키",
  minmana: "최소 마나",
  manashift: "마나 시프트",
  mana: "마나",
  lvlmana: "레벨당 마나",
  InGame: "인게임",
  delay: "딜레이",
  leftskill: "좌클릭",
  rightskill: "우클릭",
  Param1: "파라미터 1",
  Param2: "파라미터 2",
  Param3: "파라미터 3",
  Param4: "파라미터 4",
  Param5: "파라미터 5",
  Param6: "파라미터 6",
  Param7: "파라미터 7",
  Param8: "파라미터 8",
  Param9: "파라미터 9",
  Param10: "파라미터 10",
  Param11: "파라미터 11",
  Param12: "파라미터 12",
  petmax: "소환 최대 수",
  MinDam: "최소 피해",
  MaxDam: "최대 피해",
  MinLevDam1: "물리 최소 +(2–8렙)",
  MinLevDam2: "물리 최소 +(9–16렙)",
  MinLevDam3: "물리 최소 +(17–22렙)",
  MinLevDam4: "물리 최소 +(23–28렙)",
  MinLevDam5: "물리 최소 +(29렙~)",
  MaxLevDam1: "물리 최대 +(2–8렙)",
  MaxLevDam2: "물리 최대 +(9–16렙)",
  MaxLevDam3: "물리 최대 +(17–22렙)",
  MaxLevDam4: "물리 최대 +(23–28렙)",
  MaxLevDam5: "물리 최대 +(29렙~)",
  DmgSymPerCalc: "물리 시너지",
  EType: "속성",
  EMin: "속성 최소",
  EMax: "속성 최대",
  EMinLev1: "속성 최소 +(2–8렙)",
  EMinLev2: "속성 최소 +(9–16렙)",
  EMinLev3: "속성 최소 +(17–22렙)",
  EMinLev4: "속성 최소 +(23–28렙)",
  EMinLev5: "속성 최소 +(29렙~)",
  EMaxLev1: "속성 최대 +(2–8렙)",
  EMaxLev2: "속성 최대 +(9–16렙)",
  EMaxLev3: "속성 최대 +(17–22렙)",
  EMaxLev4: "속성 최대 +(23–28렙)",
  EMaxLev5: "속성 최대 +(29렙~)",
  EDmgSymPerCalc: "속성 시너지",
  ELen: "속성 지속",
  ELenSymPerCalc: "지속 시너지",
  HitShift: "히트 시프트",
  SrcDam: "무기 피해 반영",
  LevToHit: "레벨당 명중",
  ToHitCalc: "명중 계산식",
  calc1: "계산식 1",
  calc2: "계산식 2",
  calc3: "계산식 3",
  calc4: "계산식 4",
  ToHit: "명중",
  Skill1: "스킬 1",
  Sk1lvl: "스킬1 레벨",
  Skill2: "스킬 2",
  Sk2lvl: "스킬2 레벨",
  Skill3: "스킬 3",
  Sk3lvl: "스킬3 레벨",
  Skill4: "스킬 4",
  Sk4lvl: "스킬4 레벨",
  Skill5: "스킬 5",
  Sk5lvl: "스킬5 레벨",
  Skill6: "스킬 6",
  Sk6lvl: "스킬6 레벨",
  Skill7: "스킬 7",
  Sk7lvl: "스킬7 레벨",
  Skill8: "스킬 8",
  Sk8lvl: "스킬8 레벨",
  TreasureClass: "TC 노멀",
  "TreasureClass(N)": "TC 나이트메어",
  "TreasureClass(H)": "TC 헬",
  minHP: "최소 HP",
  maxHP: "최대 HP",
  "MinHP(N)": "최소 HP(NM)",
  "MaxHP(N)": "최대 HP(NM)",
  "MinHP(H)": "최소 HP(헬)",
  "MaxHP(H)": "최대 HP(헬)",
  Function: "구분",
  Uber: "우버",
  "Class Specific": "직업 전용",
  UniqueDivisor: "유니크 디바이저",
  UniqueMin: "유니크 최소",
  SetDivisor: "세트 디바이저",
  SetMin: "세트 최소",
  Item1: "아이템 1",
  Prob1: "확률 1",
  Item2: "아이템 2",
  Prob2: "확률 2",
  Item3: "아이템 3",
  Prob3: "확률 3",
  Item4: "아이템 4",
  Prob4: "확률 4",
  Item5: "아이템 5",
  Prob5: "확률 5",
  "*ItemName": "영문 이름",
  carry1: "1개만 보유",
  prop1: "속성 1",
  min1: "최소 1",
  max1: "최대 1",
  AI: "AI",
  boss: "보스",
  killable: "처치 가능",
  Velocity: "이동속도",
  Run: "달리기",
  "cost mult": "비용 배율",
  "cost add": "비용 가산",
  localdelay: "로컬 딜레이",
  globaldelay: "글로벌 딜레이",
  passive: "패시브",
  aura: "오라",
  InTown: "마을 사용",
};

export const CLASS_KO: Record<string, string> = {
  ama: "아마존",
  amazon: "아마존",
  sor: "소서리스",
  sorc: "소서리스",
  nec: "네크로맨서",
  pal: "팔라딘",
  bar: "바바리안",
  dru: "드루이드",
  ass: "어쌔신",
  war: "악마술사",
  "": "공용/몬스터",
};

export const DIFF_KO = {
  normal: "노멀",
  nightmare: "나이트메어",
  hell: "헬",
} as const;

export type Difficulty = keyof typeof DIFF_KO;

export const FIGURE_TYPES = new Set(["dols", "rdol", "odol", "dolk", "dolb"]);
export const RUNE_TYPES = new Set(["rune", "runx", "runh", "runc", "runu", "run2", "run3", "run4", "run5"]);

export function labelCol(name: string): string {
  return COL_KO[name] ?? name;
}

export function labelClass(code: string): string {
  return CLASS_KO[code.toLowerCase()] ?? (code || "공용");
}

export function isSlamtrapMonster(id: string, nameStr = ""): boolean {
  const a = id.toLowerCase();
  const b = nameStr.toLowerCase();
  return a === "slamtrap" || a.startsWith("slamtrap") || b === "slamtrap";
}

export const SKILL_EDITOR_COLS = [
  "skill",
  "charclass",
  "skilldesc",
  "reqlevel",
  "maxlvl",
  "minmana",
  "mana",
  "lvlmana",
  "manashift",
  "Param1",
  "Param2",
  "Param3",
  "Param4",
  "MinDam",
  "MaxDam",
  "EType",
  "EMin",
  "EMax",
  "ToHit",
  "InGame",
  "leftskill",
  "rightskill",
  "passive",
  "aura",
];

export const MONSTER_EDITOR_COLS = [
  "Id",
  "NameStr",
  "Level",
  "Level(N)",
  "Level(H)",
  "Skill1",
  "Sk1lvl",
  "Skill2",
  "Sk2lvl",
  "Skill3",
  "Sk3lvl",
  "Skill4",
  "Sk4lvl",
  "Skill5",
  "Sk5lvl",
  "Skill6",
  "Sk6lvl",
  "Skill7",
  "Sk7lvl",
  "Skill8",
  "Sk8lvl",
  "minHP",
  "maxHP",
  "TreasureClass",
  "TreasureClass(N)",
  "TreasureClass(H)",
];

export const UNIQUE_EDITOR_COLS = [
  "index",
  "*ItemName",
  "code",
  "rarity",
  "spawnable",
  "disabled",
  "lvl",
  "lvl req",
];

export const SET_EDITOR_COLS = [
  "index",
  "set",
  "*ItemName",
  "item",
  "rarity",
  "spawnable",
  "lvl",
  "lvl req",
];

export const MISC_EDITOR_COLS = ["name", "code", "type", "rarity", "spawnable", "level", "levelreq", "namestr"];

export const CUBE_EDITOR_COLS = ["description", "enabled", "numinputs", "input 1", "output"];

export const TC_EDITOR_COLS = [
  "Treasure Class",
  "group",
  "level",
  "Picks",
  "Unique",
  "Set",
  "Rare",
  "Magic",
  "NoDrop",
  "Item1",
  "Prob1",
  "Item2",
  "Prob2",
  "Item3",
  "Prob3",
];

export const HINTS: Record<string, string> = {
  rarity: "같은 베이스/유형 안에서 상대 확률. 숫자가 작을수록 더 잘 나옵니다.",
  Unique: "보물 클래스 유니크 품질 보정. 1024면 해당 TC에서 거의 확정 유니크입니다.",
  Set: "보물 클래스 세트 품질 보정. 1024 = 100%.",
  NoDrop: "아이템이 안 나올 가중치. 낮출수록 드랍이 많아집니다. (노드랍)",
  Picks: "한 번에 굴리는 횟수. 음수면 그만큼 확정 드랍입니다.",
  spawnable: "1이면 필드 드랍 가능, 0이면 드랍되지 않습니다.",
  disabled: "1이면 비활성(드랍 안 됨).",
  DmgSymPerCalc: "물리 피해 시너지 계산식. skill('Fire Bolt'.blvl)*par8 형식.",
  EDmgSymPerCalc: "속성 피해 시너지 계산식. 다른 스킬 투자량(blvl)을 참조합니다.",
  ELenSymPerCalc: "속성 지속시간 시너지 계산식.",
  HitShift: "피해 비트 시프트. 8이면 원본, 낮출수록 피해가 작아집니다.",
  SrcDam: "무기 피해를 스킬에 반영하는 비율(128 = 100%).",
  EMinLev1: "스킬 레벨 2~8에서, 레벨이 오를 때마다 속성 최소 피해에 더합니다. (7회)",
  EMinLev2: "스킬 레벨 9~16에서 레벨당 속성 최소 가산. (8회)",
  EMinLev3: "스킬 레벨 17~22에서 레벨당 속성 최소 가산. (6회)",
  EMinLev4: "스킬 레벨 23~28에서 레벨당 속성 최소 가산. (6회)",
  EMinLev5: "스킬 레벨 29 이상에서 레벨당 속성 최소 가산.",
  EMaxLev1: "스킬 레벨 2~8에서, 레벨이 오를 때마다 속성 최대 피해에 더합니다. (7회)",
  EMaxLev2: "스킬 레벨 9~16에서 레벨당 속성 최대 가산. (8회)",
  EMaxLev3: "스킬 레벨 17~22에서 레벨당 속성 최대 가산. (6회)",
  EMaxLev4: "스킬 레벨 23~28에서 레벨당 속성 최대 가산. (6회)",
  EMaxLev5: "스킬 레벨 29 이상에서 레벨당 속성 최대 가산.",
  EMin: "스킬 레벨 1의 속성 최소 피해.",
  EMax: "스킬 레벨 1의 속성 최대 피해.",
};
